# Users have a name, several grouped interests and an expected target cluster
# Target clusters are: musical, sporty, hipster, foodie, geek

# Interest pool:
# music:
#
# sport:
#
# food:
#
# tech:
#
#













0:
  name: Mr Smith
  interests:
    music: ""
    sport:
    food:
    tech:
  target: sporty

